SET NOCOUNT ON
GO

IF ((SELECT dbid FROM sysdatabases WHERE name = 'AccessControl') is null)
BEGIN
-- Create and switch to the database if it doesn't already exist
IF DB_ID('AccessControl') IS NULL AND ('$(SQLCMDDBNAME)' IN ('', 'master') OR SUBSTRING('$(SQLCMDDBNAME)', 1, 1) = '$')
	CREATE DATABASE [AccessControl]
END
GO
IF DB_ID('AccessControl') IS NOT NULL AND ('$(SQLCMDDBNAME)' IN ('', 'master') OR SUBSTRING('$(SQLCMDDBNAME)', 1, 1) = '$')
	USE [AccessControl]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE CURRENT SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE CURRENT SET ANSI_NULLS OFF 
GO
ALTER DATABASE CURRENT SET ANSI_PADDING OFF 
GO
ALTER DATABASE CURRENT SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE CURRENT SET ARITHABORT OFF 
GO
ALTER DATABASE CURRENT SET AUTO_CLOSE OFF 
GO
ALTER DATABASE CURRENT SET AUTO_SHRINK OFF 
GO
ALTER DATABASE CURRENT SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE CURRENT SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE CURRENT SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE CURRENT SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE CURRENT SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE CURRENT SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE CURRENT SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE CURRENT SET  DISABLE_BROKER 
GO
ALTER DATABASE CURRENT SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE CURRENT SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE CURRENT SET TRUSTWORTHY OFF 
GO
ALTER DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE CURRENT SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE CURRENT SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE CURRENT SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE CURRENT SET RECOVERY SIMPLE 
GO
ALTER DATABASE CURRENT SET  MULTI_USER 
GO
ALTER DATABASE CURRENT SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE CURRENT SET DB_CHAINING OFF 
GO
ALTER DATABASE CURRENT SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE CURRENT SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE CURRENT SET DELAYED_DURABILITY = DISABLED 
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
